server:
  port: 8081
  servlet:
    session:
      timeout: 120m
spring:
  application:
    name: '不动产中心OA'
  aop:
    auto: true
  profiles:
    active: ${env}
  thymeleaf:
    prefix: classpath:/templates/
    check-template-location: true
    suffix: .html
    encoding: UTF-8
    mode: HTML5
    cache: false
    servlet:
      content-type: text/html
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    format:
      date-time: yyyy-MM-dd HH:mm:ss
      date: yyyy-MM-dd
      time: HH:mm:ss
  devtools:
    restart:
      enabled: true